Added a z-index to the Authors name
somedevsdo/blog pull request #87
Opened 2021-06-12 19:58 UTC by davidn0rman

Resolves #86

Noticed on a post the authors name clipped below the top bar thing. Simple z-index application should do the trick. Tested the other places I know this component comes up and all looks fine.

2021-06-12 22:18 UTC, andrewbarnesweb requested changes
❤️. My bad.

Commented on issue, but this was a prop issue. Should be a less impactful change to add `vertical` prop.

2021-06-13 17:26 UTC, andrewbarnesweb commented
Happy to make the change if you want?

2021-06-13 19:22 UTC, davidn0rman commented
I should have referenced Figma really... I see what you mean now. Should be fixed. :)

Means the one on the homepage is wrong then? 
![image](https://user-images.githubusercontent.com/20046480/121819443-01550d80-cc85-11eb-9872-86addeb36dc0.png)

2021-06-13 19:34 UTC, andrewbarnesweb commented
Yep. I made a real hash of those changes 🛌

2021-06-13 19:38 UTC, andrewbarnesweb approved these changes
👍🏽

2021-06-13 20:54 UTC, merged